### ISSUE TITLE
Wrong Number Version in Console

### ISSUE THREAD

**Issue by Nogapra** [MrLetsplay2003/MrCore#5] opened 2018-11-12 08:30 UTC
Hello,
I'm Using last Release of 1.11 MrCore
And Spigot 1.13.2 : 
 
[09:21:34] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2474d93-ca22de3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[09:21:34] [Server thread/INFO]: Checking version, please wait...
[09:21:35] [Thread-9/INFO]: You are 5 version(s) behind.

This is not a big problem, but when starting the server I have this display that appears that tells me that I do not use the correct version, with a download link to be able to recover the correct version, what I did.

But I still have the same anomaly 

[MrCore_BukkitImpl] Enabling MrCore_BukkitImpl v1.1
[09:19:38] [Server thread/INFO]: [MrCore_BukkitImpl] Applying compat for MC 1.13 Release 2 / V1_13_R2
[09:19:39] [Server thread/INFO]: [MrCore_BukkitImpl] **The current version (1.10) does not match the required one (latest/1.11)**
[09:19:39] [Server thread/INFO]: [MrCore_BukkitImpl] You can download the required version here: https://github.com/MrLetsplay2003/MrCore/releases/download/1.11/MrCore_1.11.jar
[09:19:39] [Server thread/INFO]: [MrCore_BukkitImpl] And MrCore is on board as well! :wave:

Could you fix the version number in the plugin, thank you very much.

Kind regards

**Comment by MrLetsplay2003** [comment] 2018-11-12 12:59
This will be fixed in the next release of MrCore (will be released within the next few days)

**Comment by MrLetsplay2003** [comment] 2018-12-03 14:08
The issue is fixed in v2.0b

**Closed by MrLetsplay2003** 2018-12-03 14:08 UTC
Labels: bug
